### PR TITLE
Update glob, mocha, should and vinyl

### PR DESCRIPTION
**Pull request by arzafran**
## Background
Dependencies where really outdated
## Changes done
- Update glob to 7.1.1
- Update mocha to 3.3.0
- Update should to 11.2.1
- Update vinyl to 2.0.2
## Notes
Thanks for your work mate!

### CODE REVIEW

**Comment by jsahlen** [comment]
Hey there. Sorry for taking so long to respond! Thank you for the pull request, but the reason that the dependencies are so outdated is that I've completely stopped development and support for `gulp-css-globbing`, including releasing new versions, and as such I'm not accepting really pull requests either. However, if you or anyone else would be interested in making new releases, I'd be more than happy to hand over ownership of the NPM module! Please let me know if that would be an option.

**Comment by arzafran** [comment]
Sure! I'm glad to contribute to this package and even mantain it. once again thanks for your work, and just tell me when you're ready to hand over the ownership and I'll update the dependencies, and take a deeper look at the codebase to see if there's anything else needed.
Thanks once again for taking the harder step (the first one).

**Comment by jsahlen** [comment]
@arzafran Apologies once again for the long response time. Happy to hear you're willing to take over maintenance! :) I've added you as a collaborator for the NPM module. Please release away, and feel free to update the upstream URLs and such in the `package.json` to your fork. Thanks!

**Comment by arzafran** [comment]
@jsahlen now it's my fault I haven't replied earlier, terribly sorry about that. Ok I'll point the package.json to my fork, and start mantaining it there. Thanks for your work!

**Pull request closed without merging**
